name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build and start services
        run: docker compose up --build -d

      - name: Wait for services to start
        run: |
          echo "Waiting for service to be ready..."
          for i in {1..30}; do
            if curl -s http://localhost:8000/healthz > /dev/null; then
              echo "Service is up!"
              break
            fi
            echo "Service not ready yet... retrying in 2 seconds"
            sleep 2
          done
          
      - name: Verify /health endpoint returns HTTP 200
        run: |
          echo "Checking /health endpoint..."
          http_status=$(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:8000/health)
          if [ "$http_status" -ne 200 ]; then
            echo "Expected HTTP 200 but got $http_status"
            exit 1
          fi
          echo "✅ /health returned HTTP 200"
          
      - name: Stop docker container and Clean up
        if: always()
        run: docker compose down
